# Generated by Django 5.2.17 on 2026-08-15 19:34

import apps.links.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=apps.links.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_ghs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_fee_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fee_handling', models.CharField(choices=[('ABSORB_FEE', 'Absorb Fee (Seller pays)'), ('PASS_TO_BUYER', 'Pass to Buyer (Buyer pays)')], default='PASS_TO_BUYER', max_length=20)),
                ('intended_buyer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
