# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
