# Generated by Django 5.1.7 on 2026-08-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_paymentlink_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
