# Generated by Django 5.1.7 on 2026-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_paymentlink_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
