# Generated by Django 5.2.17 on 2026-09-29 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_paymentlink_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='direct_order_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid & In Escrow'), ('DECLINED', 'Declined by Buyer'), ('CANCELLED', 'Cancelled by Seller')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='intended_buyer',
            field=models.ForeignKey(blank=True, help_text='Target platform buyer if this order was sent directly within the platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payment_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='is_direct_order',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['intended_buyer', 'is_direct_order', 'direct_order_status'], name='links_payme_intende_315046_idx'),
        ),
    ]
