# Generated by Django 5.2.17 on 2026-08-15 22:49

import apps.notifications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-App')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
