# Generated by Django 5.1.7 on 2026-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_broadcastcampaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
