# Generated by Django 5.2.17 on 2026-08-15 19:34

import apps.escrow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('shipping_address', models.TextField(blank=True)),
                ('total_amount_ghs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee_ghs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('INSPECTION_PERIOD', 'Inspection Period'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed')], default='AWAITING_PAYMENT', max_length=30)),
                ('paystack_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='links.paymentlink')),
            ],
        ),
    ]
