# Generated by Django 5.2.17 on 2026-08-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='inspection_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
