# Generated by Django 5.2.17 on 2026-08-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_transaction_delivered_at_transaction_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('INSPECTION_PERIOD', 'Inspection Period'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='AWAITING_PAYMENT', max_length=30),
        ),
    ]
