# Generated by Django 5.2.17 on 2026-08-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('INSPECTION_PERIOD', 'Inspection Period'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='AWAITING_PAYMENT', max_length=30),
        ),
    ]
