# Generated by Django 5.1.7 on 2026-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
