# Generated by Django 5.2.17 on 2026-08-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_transaction_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
