# Generated by Django 5.2.17 on 2026-08-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_transaction_delivery_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reminder_30h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reminder_36h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reminder_42h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
