# Generated by Django 5.1.7 on 2026-08-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0007_add_time_and_id_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reminder_42h_sent',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_dispute_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manager_dispute_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manager_dispute_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_dispute_photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_dispute_response',
            field=models.TextField(blank=True),
        ),
    ]
