# Generated by Django 5.1.7 on 2026-08-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0008_remove_transaction_reminder_42h_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reminder_42h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
