# Generated by Django 5.1.7 on 2026-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0009_transaction_reminder_42h_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
