# Generated by Django 5.2.17 on 2026-09-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0010_platformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reminder_6h_dispatch_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reminder_6h_inspection_sent',
            field=models.BooleanField(default=False),
        ),
    ]
