# Generated by Django 5.2.17 on 2026-09-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0011_transaction_reminder_6h_dispatch_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='return_carrier_tracking_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_courier_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_delivery_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_destination_station',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_driver_car_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_driver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='return_waybill_photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('INSPECTION_PERIOD', 'Inspection Period'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('RETURN_IN_PROGRESS', 'Return In Progress'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='AWAITING_PAYMENT', max_length=30),
        ),
    ]
