# Generated by Django 5.1.7 on 2026-09-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0012_transaction_return_carrier_tracking_url_and_more'),
        ('links', '0004_alter_paymentlink_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='buyer_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer_phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAYMENT_RECEIVED', 'Payment Received'), ('DELIVERY_IN_PROGRESS', 'Delivery In Progress'), ('INSPECTION_PERIOD', 'Inspection Period'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('RETURN_IN_PROGRESS', 'Return In Progress'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='AWAITING_PAYMENT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='escrow_tran_status_65f6a4_idx'),
        ),
    ]
