# Generated by Django 5.1.7 on 2026-09-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0013_alter_transaction_buyer_email_and_more'),
        ('links', '0004_alter_paymentlink_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'is_archived', 'created_at'], name='escrow_tran_status_007d49_idx'),
        ),
    ]
