# Generated by Django 5.1.7 on 2026-09-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0014_transaction_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_review_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
