# Generated by Django 5.1.7 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0015_transaction_buyer_review_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='auto_cancelled_non_dispatch',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reminder_24h_dispatch_sent',
            field=models.BooleanField(default=False),
        ),
    ]
