# Generated by Django 5.1.7 on 2026-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0016_transaction_auto_cancelled_non_dispatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dispute_retracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
