# Generated by Django 5.2.17 on 2026-09-20 02:25

import apps.escrow.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0017_transaction_dispute_retracted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='assigned_arbiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dispute_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArbiterPayoutBatch',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('total_amount_ghs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activity_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=20)),
                ('payout_method', models.CharField(default='MOMO', max_length=20)),
                ('payout_account_details', models.JSONField(blank=True, default=dict)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_batches', to=settings.AUTH_USER_MODEL)),
                ('finance_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_arbiter_payout_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolutionAction',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ASSIGNED', 'Arbiter Assigned'), ('MESSAGE_APPENDED', 'Message / Evidence Appended'), ('RELEASE_TO_SELLER', 'Released to Seller'), ('FULL_REFUND_TO_BUYER', 'Full Refund to Buyer'), ('PARTIAL_REFUND_TO_BUYER', 'Partial Refund Settlement'), ('REQUIRE_RETURN_FROM_BUYER', 'Return Required From Buyer'), ('RETRACTED_CONFIRMED', 'Retraction Confirmed')], db_index=True, max_length=40)),
                ('admin_notes', models.TextField(blank=True)),
                ('manager_photos', models.JSONField(blank=True, default=list)),
                ('refund_amount_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('seller_amount_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('platform_retained_fee_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('arbiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbiter_dispute_actions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_actions', to='escrow.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArbiterActivityLog',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('DISPUTE_RESOLVED', 'Dispute Resolved'), ('COMPLIANCE_REVIEW', 'Compliance Review Completed'), ('MEDIATION_INTERVENTION', 'Mediation Intervention')], db_index=True, default='DISPUTE_RESOLVED', max_length=40)),
                ('fee_rate_ghs', models.DecimalField(decimal_places=2, default=25.0, help_text='Configured compensation fee in GHS for this resolved task.', max_digits=10)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved for Payout'), ('PAID', 'Paid / Settled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_arbiter_activities', to=settings.AUTH_USER_MODEL)),
                ('arbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbiter_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbiter_activity_logs', to='escrow.transaction')),
                ('payout_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='escrow.arbiterpayoutbatch')),
                ('resolution_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='escrow.disputeresolutionaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
