# Generated by Django 5.1.7 on 2026-09-20 15:09

import apps.escrow.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0018_transaction_assigned_arbiter_arbiterpayoutbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerIdentity',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('primary_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('available_credit_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lifetime_credit_earned_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lifetime_credit_redeemed_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_discount_ghs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='promo_discount_ghs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='BuyerCreditLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount_ghs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('EARNED', 'Loyalty Reward Earned'), ('REFERRAL_BONUS', 'Referral Bonus'), ('ADMIN_GRANT', 'Admin Discretionary Grant'), ('RESERVED', 'Reserved for Checkout'), ('REDEEMED', 'Redeemed at Checkout'), ('RELEASED', 'Released from Abandoned Checkout'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed on Refund')], max_length=30)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger_entries', to='escrow.buyeridentity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='escrow.buyeridentity'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage on Platform Fee'), ('FIXED_GHS', 'Fixed Amount (GHS)')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount_cap_ghs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_amount_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('per_buyer_limit', models.IntegerField(default=1)),
                ('eligible_role', models.CharField(choices=[('ALL', 'All Users & Buyers'), ('BUYER_ONLY', 'Buyers Only'), ('SELLER_ONLY', 'Sellers Only')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='escrow.promocode'),
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('discount_applied_ghs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to='escrow.buyeridentity')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='escrow.promocode')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_promo_redemptions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='escrow.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='SellerRewardLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount_ghs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('EARNED', 'Milestone Fee Reward Earned'), ('REFERRAL_BONUS', 'Referral Bonus'), ('ADMIN_GRANT', 'Admin Discretionary Grant'), ('REDEEMED', 'Redeemed to Offset Platform Fee'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed on Refund')], max_length=30)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
