# Generated by Django 5.1.7 on 2026-09-21 04:47

import apps.escrow.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0019_buyeridentity_transaction_credit_discount_ghs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='seasonal_fee_discount_ghs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_fee_offset_applied_ghs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SeasonalFeeCampaign',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('fee_rule_type', models.CharField(choices=[('WAIVED', '100% Waived (Zero Platform Fee)'), ('REDUCED_PERCENTAGE', 'Reduced Variable Fee %'), ('REDUCED_FIXED', 'Reduced Fixed Fee GHS'), ('PERCENTAGE_DISCOUNT', 'Percentage Discount on Total Fee'), ('FIXED_DISCOUNT', 'Fixed GHS Discount on Total Fee')], default='WAIVED', max_length=30)),
                ('rule_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_order_amount_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_discount_cap_ghs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seasonal_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='seasonal_fee_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='escrow.seasonalfeecampaign'),
        ),
        migrations.CreateModel(
            name='TransactionRewardCampaign',
            fields=[
                ('id', models.UUIDField(default=apps.escrow.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('target_role', models.CharField(choices=[('SELLER', 'Sellers Only'), ('BUYER', 'Buyers Only'), ('ALL', 'All Participants')], default='SELLER', max_length=20)),
                ('reward_type', models.CharField(choices=[('FIXED_GHS', 'Fixed Amount (GHS) per Order'), ('PERCENTAGE_OF_ORDER', 'Percentage of Order Total'), ('PERCENTAGE_OF_FEE', 'Percentage of Platform Fee')], default='FIXED_GHS', max_length=30)),
                ('reward_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_reward_cap_ghs', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('validity_days', models.IntegerField(default=180)),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reward_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
