# Generated by Django 5.1.7 on 2026-09-27 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0020_transaction_seasonal_fee_discount_ghs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='arbiter_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='arbiter_escalated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_dispute_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='arbiter_escalated_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_dispute_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_arbitration_order_url',
            field=models.TextField(blank=True),
        ),
    ]
