# Generated by Django 5.2.17 on 2026-10-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0021_transaction_arbiter_escalated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeresolutionaction',
            name='action_type',
            field=models.CharField(choices=[('ASSIGNED', 'Arbiter Assigned'), ('MESSAGE_APPENDED', 'Message / Evidence Appended'), ('ARBITER_INSTRUCTION', 'Arbiter Instruction / Notice'), ('RELEASE_TO_SELLER', 'Released to Seller'), ('FULL_REFUND_TO_BUYER', 'Full Refund to Buyer'), ('PARTIAL_REFUND_TO_BUYER', 'Partial Refund Settlement'), ('REQUIRE_RETURN_FROM_BUYER', 'Return Required From Buyer'), ('RETRACTED_CONFIRMED', 'Retraction Confirmed')], db_index=True, max_length=40),
        ),
    ]
