# Generated by Django 5.1.7 on 2026-10-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0022_alter_disputeresolutionaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_auto_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_fee_deducted_ghs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_refund_amount_ghs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_refund_target',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
