# Generated by Django 5.1.7 on 2026-10-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0023_transaction_buyer_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancellation_grace_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_payout_hold_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_payout_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=35),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_seller_carrier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_seller_proof_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_seller_proof_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_seller_reported_shipped',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellation_seller_waybill',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='buyercreditledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('EARNED', 'Loyalty Reward Earned'), ('REFERRAL_BONUS', 'Referral Bonus'), ('ADMIN_GRANT', 'Admin Discretionary Grant'), ('ORDER_CANCEL_REFUND', 'Refund from Cancelled Order'), ('RESERVED', 'Reserved for Checkout'), ('REDEEMED', 'Redeemed at Checkout'), ('RELEASED', 'Released from Abandoned Checkout'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed on Refund')], max_length=30),
        ),
    ]
