# Generated by Django 5.2.17 on 2026-08-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_mode',
            field=models.CharField(choices=[('INSTANT', 'Instant Payout'), ('MANUAL', 'Manual Withdrawal')], default='INSTANT', help_text='Whether completed transactions are paid out instantly or held for manual withdrawal.', max_length=10),
        ),
    ]
