# Generated by Django 5.1.7 on 2026-08-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_payout_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advertised_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp until which the shop is featured as a paid ad.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_category',
            field=models.CharField(blank=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
