# Generated by Django 5.1.7 on 2026-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_advertised_until_user_shop_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_license_photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id_photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_categories',
            field=models.JSONField(blank=True, default=list, help_text='Up to 3 product categories associated with this shop.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('UNSUBMITTED', 'Unsubmitted'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Verified & Approved'), ('REJECTED', 'Rejected')], default='UNSUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
