# Generated by Django 5.1.7 on 2026-09-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_phone_verified_user_phone_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA Authenticator app is enabled for this account.'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Encrypted or Base32 TOTP secret for authenticator apps.', max_length=64),
        ),
    ]
