# Generated by Django 5.1.7 on 2026-09-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_2fa_enabled_user_totp_last_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('ADMIN', 'Admin'), ('SUPPORT_AGENT', 'Support Agent')], db_index=True, default='BUYER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_category',
            field=models.CharField(blank=True, db_index=True, default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('UNSUBMITTED', 'Unsubmitted'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Verified & Approved'), ('REJECTED', 'Rejected')], db_index=True, default='UNSUBMITTED', max_length=20),
        ),
    ]
