# Generated by Django 5.1.7 on 2026-09-15 00:39

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_suspended_user_suspended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionAppeal',
            fields=[
                ('id', models.UUIDField(default=apps.users.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='User explanation and appeal justification')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Reinstated'), ('REJECTED', 'Appeal Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes/reasoning provided by admin upon review')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspension_appeals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
