# Generated by Django 5.1.7 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_suspensionappeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reinstated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
