# Generated by Django 5.2.17 on 2026-09-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_reinstated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('ADMIN', 'Admin / HR Manager'), ('ARBITER', 'Dispute Arbiter'), ('COMPLIANCE_OFFICER', 'KYC / Compliance Officer'), ('FINANCE_ADMIN', 'Finance Admin / Accountant'), ('SUPPORT_AGENT', 'Support Agent')], db_index=True, default='BUYER', max_length=20),
        ),
    ]
