# Generated by Django 5.1.7 on 2026-09-20 13:04

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0018_transaction_assigned_arbiter_arbiterpayoutbatch_and_more'),
        ('users', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_referees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_bonus_credits_ghs',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Referral discount & promotional credit balance', max_digits=12),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=apps.users.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('code_used', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending First Transaction'), ('COMPLETED', 'Completed & Rewarded'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('reward_amount_ghs', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('referee_discount_ghs', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_awards', to='escrow.transaction')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
