# Generated by Django 5.1.7 on 2026-09-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_referral_code_user_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_shipping_address',
            field=models.TextField(blank=True, default='', help_text='Default shipping and delivery address for buyer checkout prefilling.'),
        ),
    ]
