# Generated by Django 5.2.17 on 2026-08-15 20:49

import apps.delivery.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0002_transaction_delivered_at_transaction_dispatched_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.UUIDField(default=apps.delivery.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('COURIER_API', 'Courier API'), ('INFORMAL_BUS', 'Informal Bus Transport')], max_length=20)),
                ('courier_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_station', models.CharField(blank=True, max_length=255, null=True)),
                ('waybill_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='escrow.transaction')),
            ],
        ),
    ]
