# Generated by Django 5.2.17 on 2026-08-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='driver_car_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
