# Generated by Django 5.2.17 on 2026-08-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_add_driver_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='buyer_id_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
