# Generated by Django 5.2.17 on 2026-08-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_add_time_and_id_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylog',
            name='buyer_id_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverylog',
            name='waybill_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
