# Generated by Django 5.1.7 on 2026-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliverylog_buyer_id_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='carrier_code',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('EMS', 'EMS / Ghana Post'), ('OTHERS', 'Others')], default='OTHERS', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='carrier_tracking_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
