# Generated by Django 5.1.7 on 2026-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliverylog_carrier_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylog',
            name='carrier_code',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL Express'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('EMS', 'EMS / Ghana Post'), ('SPEEDAF', 'Speedaf Express'), ('OTHERS', 'Others')], default='OTHERS', max_length=20, null=True),
        ),
    ]
