# Generated by Django 5.2.17 on 2026-08-15 22:04

import apps.wallet.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.UUIDField(default=apps.wallet.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('available_balance_ghs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('momo_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_wallets', to='ledger.ledgeraccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
