# Generated by Django 5.2.17 on 2026-08-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='preferred_payout_type',
            field=models.CharField(choices=[('MOMO', 'Mobile Money'), ('BANK', 'Bank Account')], default='MOMO', max_length=10),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='total_paystack_fees_ghs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
