# Generated by Django 5.1.7 on 2026-09-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_sellerwallet_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerwallet',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerwallet',
            name='bank_name_matched',
            field=models.BooleanField(default=True),
        ),
    ]
