# Generated by Django 5.1.7 on 2026-08-22 07:00

import apps.reviews.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0009_transaction_reminder_42h_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.UUIDField(default=apps.reviews.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('rating_speed', models.PositiveSmallIntegerField(default=5)),
                ('rating_communication', models.PositiveSmallIntegerField(default=5)),
                ('rating_overall', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('seller_reply', models.TextField(blank=True)),
                ('seller_replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Automatically set to False if a dispute is raised for this transaction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='escrow.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
