# Generated by Django 5.1.7 on 2026-09-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_sellerreview_downvotes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
