# Generated by Django 5.1.7 on 2026-09-11 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0013_alter_transaction_buyer_email_and_more'),
        ('reviews', '0003_sellerreview_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Automatically set to False if a dispute is raised for this transaction.'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['seller', 'is_active'], name='reviews_sel_seller__01d59c_idx'),
        ),
    ]
