# Generated by Django 5.1.7 on 2026-09-12 10:10

import apps.reviews.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_sellerreview_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAdInvoice',
            fields=[
                ('id', models.UUIDField(default=apps.reviews.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('amount_ghs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='WALLET', max_length=30)),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('advertised_from', models.DateTimeField()),
                ('advertised_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
