# Generated by Django 5.1.7 on 2026-09-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_shopadinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks the number of times the review has been edited/updated.'),
        ),
    ]
